/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminAppRouteRouteImport } from './routes/admin/_app/route'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminNoAccessRouteImport } from './routes/admin/no-access'
import { Route as AdminSetupRouteImport } from './routes/admin/setup'
import { Route as BuildYourTripIndexRouteImport } from './routes/build-your-trip.index'
import { Route as BuildYourTripProductIdRouteImport } from './routes/build-your-trip.$productId'
import { Route as PagesSlugRouteImport } from './routes/pages.$slug'
import { Route as PurchasePurchaseIdRouteImport } from './routes/purchase.$purchaseId'
import { Route as AdminAppIndexRouteImport } from './routes/admin/_app/index'
import { Route as AdminAppCatalogTaxonomyRouteImport } from './routes/admin/_app/catalog-taxonomy'
import { Route as AdminAppComponentTemplatesRouteImport } from './routes/admin/_app/component-templates'
import { Route as AdminAppCustomersRouteImport } from './routes/admin/_app/customers'
import { Route as AdminAppExperiencesRouteImport } from './routes/admin/_app/experiences'
import { Route as AdminAppInsuranceRouteImport } from './routes/admin/_app/insurance'
import { Route as AdminAppPricesRouteImport } from './routes/admin/_app/prices'
import { Route as AdminAppPromoCodesRouteImport } from './routes/admin/_app/promo-codes'
import { Route as AdminAppReviewsRouteImport } from './routes/admin/_app/reviews'
import { Route as AdminAppTeamRouteImport } from './routes/admin/_app/team'
import { Route as AdminAppHotelsIndexRouteImport } from './routes/admin/_app/hotels.index'
import { Route as AdminAppHotelsAccommodationIdRouteImport } from './routes/admin/_app/hotels.$accommodationId'
import { Route as AdminAppMotorbikesIndexRouteImport } from './routes/admin/_app/motorbikes.index'
import { Route as AdminAppMotorbikesMotorbikeIdRouteImport } from './routes/admin/_app/motorbikes.$motorbikeId'
import { Route as AdminAppOrdersIndexRouteImport } from './routes/admin/_app/orders.index'
import { Route as AdminAppOrdersPurchaseIdRouteImport } from './routes/admin/_app/orders.$purchaseId'
import { Route as AdminAppProductsIndexRouteImport } from './routes/admin/_app/products.index'
import { Route as AdminAppProductsProductIdRouteImport } from './routes/admin/_app/products.$productId'
import { Route as AdminAppSettingsIndexRouteImport } from './routes/admin/_app/settings.index'
import { Route as AdminAppSettingsAuditRouteImport } from './routes/admin/_app/settings.audit'
import { Route as AdminAppSettingsCurrenciesRouteImport } from './routes/admin/_app/settings.currencies'
import { Route as AdminAppSettingsLanguagesRouteImport } from './routes/admin/_app/settings.languages'
import { Route as AdminAppSettingsMarketsRouteImport } from './routes/admin/_app/settings.markets'
import { Route as AdminAppSettingsUsersRouteImport } from './routes/admin/_app/settings.users'
import { Route as AdminAppTransportIndexRouteImport } from './routes/admin/_app/transport.index'
import { Route as AdminAppTransportTransportIdRouteImport } from './routes/admin/_app/transport.$transportId'
import { Route as AdminAppVouchersIndexRouteImport } from './routes/admin/_app/vouchers.index'
import { Route as AdminAppVouchersVoucherIdRouteImport } from './routes/admin/_app/vouchers.$voucherId'
import { Route as ApiPublicPaymentsXenditRouteImport } from './routes/api/public/payments/xendit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppRouteRoute = AdminAppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminNoAccessRoute = AdminNoAccessRouteImport.update({
  id: '/no-access',
  path: '/no-access',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRouteRoute,
} as any)
const BuildYourTripIndexRoute = BuildYourTripIndexRouteImport.update({
  id: '/build-your-trip/',
  path: '/build-your-trip/',
  getParentRoute: () => rootRouteImport,
} as any)
const BuildYourTripProductIdRoute = BuildYourTripProductIdRouteImport.update({
  id: '/build-your-trip/$productId',
  path: '/build-your-trip/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PagesSlugRoute = PagesSlugRouteImport.update({
  id: '/pages/$slug',
  path: '/pages/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PurchasePurchaseIdRoute = PurchasePurchaseIdRouteImport.update({
  id: '/purchase/$purchaseId',
  path: '/purchase/$purchaseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppIndexRoute = AdminAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppCatalogTaxonomyRoute = AdminAppCatalogTaxonomyRouteImport.update({
  id: '/catalog-taxonomy',
  path: '/catalog-taxonomy',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppComponentTemplatesRoute =
  AdminAppComponentTemplatesRouteImport.update({
    id: '/component-templates',
    path: '/component-templates',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppCustomersRoute = AdminAppCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppExperiencesRoute = AdminAppExperiencesRouteImport.update({
  id: '/experiences',
  path: '/experiences',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppInsuranceRoute = AdminAppInsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppPricesRoute = AdminAppPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppPromoCodesRoute = AdminAppPromoCodesRouteImport.update({
  id: '/promo-codes',
  path: '/promo-codes',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppReviewsRoute = AdminAppReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppTeamRoute = AdminAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppHotelsIndexRoute = AdminAppHotelsIndexRouteImport.update({
  id: '/hotels/',
  path: '/hotels/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppHotelsAccommodationIdRoute =
  AdminAppHotelsAccommodationIdRouteImport.update({
    id: '/hotels/$accommodationId',
    path: '/hotels/$accommodationId',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppMotorbikesIndexRoute = AdminAppMotorbikesIndexRouteImport.update({
  id: '/motorbikes/',
  path: '/motorbikes/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppMotorbikesMotorbikeIdRoute =
  AdminAppMotorbikesMotorbikeIdRouteImport.update({
    id: '/motorbikes/$motorbikeId',
    path: '/motorbikes/$motorbikeId',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppOrdersIndexRoute = AdminAppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppOrdersPurchaseIdRoute =
  AdminAppOrdersPurchaseIdRouteImport.update({
    id: '/orders/$purchaseId',
    path: '/orders/$purchaseId',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppProductsIndexRoute = AdminAppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppProductsProductIdRoute =
  AdminAppProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppSettingsIndexRoute = AdminAppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppSettingsAuditRoute = AdminAppSettingsAuditRouteImport.update({
  id: '/settings/audit',
  path: '/settings/audit',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppSettingsCurrenciesRoute =
  AdminAppSettingsCurrenciesRouteImport.update({
    id: '/settings/currencies',
    path: '/settings/currencies',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppSettingsLanguagesRoute =
  AdminAppSettingsLanguagesRouteImport.update({
    id: '/settings/languages',
    path: '/settings/languages',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppSettingsMarketsRoute = AdminAppSettingsMarketsRouteImport.update({
  id: '/settings/markets',
  path: '/settings/markets',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppSettingsUsersRoute = AdminAppSettingsUsersRouteImport.update({
  id: '/settings/users',
  path: '/settings/users',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppTransportIndexRoute = AdminAppTransportIndexRouteImport.update({
  id: '/transport/',
  path: '/transport/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppTransportTransportIdRoute =
  AdminAppTransportTransportIdRouteImport.update({
    id: '/transport/$transportId',
    path: '/transport/$transportId',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const AdminAppVouchersIndexRoute = AdminAppVouchersIndexRouteImport.update({
  id: '/vouchers/',
  path: '/vouchers/',
  getParentRoute: () => AdminAppRouteRoute,
} as any)
const AdminAppVouchersVoucherIdRoute =
  AdminAppVouchersVoucherIdRouteImport.update({
    id: '/vouchers/$voucherId',
    path: '/vouchers/$voucherId',
    getParentRoute: () => AdminAppRouteRoute,
  } as any)
const ApiPublicPaymentsXenditRoute = ApiPublicPaymentsXenditRouteImport.update({
  id: '/api/public/payments/xendit',
  path: '/api/public/payments/xendit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/no-access': typeof AdminNoAccessRoute
  '/admin/setup': typeof AdminSetupRoute
  '/build-your-trip/$productId': typeof BuildYourTripProductIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/purchase/$purchaseId': typeof PurchasePurchaseIdRoute
  '/build-your-trip/': typeof BuildYourTripIndexRoute
  '/admin/catalog-taxonomy': typeof AdminAppCatalogTaxonomyRoute
  '/admin/component-templates': typeof AdminAppComponentTemplatesRoute
  '/admin/customers': typeof AdminAppCustomersRoute
  '/admin/experiences': typeof AdminAppExperiencesRoute
  '/admin/insurance': typeof AdminAppInsuranceRoute
  '/admin/prices': typeof AdminAppPricesRoute
  '/admin/promo-codes': typeof AdminAppPromoCodesRoute
  '/admin/reviews': typeof AdminAppReviewsRoute
  '/admin/team': typeof AdminAppTeamRoute
  '/admin/': typeof AdminAppIndexRoute
  '/admin/hotels/$accommodationId': typeof AdminAppHotelsAccommodationIdRoute
  '/admin/motorbikes/$motorbikeId': typeof AdminAppMotorbikesMotorbikeIdRoute
  '/admin/orders/$purchaseId': typeof AdminAppOrdersPurchaseIdRoute
  '/admin/products/$productId': typeof AdminAppProductsProductIdRoute
  '/admin/settings/audit': typeof AdminAppSettingsAuditRoute
  '/admin/settings/currencies': typeof AdminAppSettingsCurrenciesRoute
  '/admin/settings/languages': typeof AdminAppSettingsLanguagesRoute
  '/admin/settings/markets': typeof AdminAppSettingsMarketsRoute
  '/admin/settings/users': typeof AdminAppSettingsUsersRoute
  '/admin/transport/$transportId': typeof AdminAppTransportTransportIdRoute
  '/admin/vouchers/$voucherId': typeof AdminAppVouchersVoucherIdRoute
  '/api/public/payments/xendit': typeof ApiPublicPaymentsXenditRoute
  '/admin/hotels/': typeof AdminAppHotelsIndexRoute
  '/admin/motorbikes/': typeof AdminAppMotorbikesIndexRoute
  '/admin/orders/': typeof AdminAppOrdersIndexRoute
  '/admin/products/': typeof AdminAppProductsIndexRoute
  '/admin/settings/': typeof AdminAppSettingsIndexRoute
  '/admin/transport/': typeof AdminAppTransportIndexRoute
  '/admin/vouchers/': typeof AdminAppVouchersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminAppIndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/no-access': typeof AdminNoAccessRoute
  '/admin/setup': typeof AdminSetupRoute
  '/build-your-trip/$productId': typeof BuildYourTripProductIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/purchase/$purchaseId': typeof PurchasePurchaseIdRoute
  '/build-your-trip': typeof BuildYourTripIndexRoute
  '/admin/catalog-taxonomy': typeof AdminAppCatalogTaxonomyRoute
  '/admin/component-templates': typeof AdminAppComponentTemplatesRoute
  '/admin/customers': typeof AdminAppCustomersRoute
  '/admin/experiences': typeof AdminAppExperiencesRoute
  '/admin/insurance': typeof AdminAppInsuranceRoute
  '/admin/prices': typeof AdminAppPricesRoute
  '/admin/promo-codes': typeof AdminAppPromoCodesRoute
  '/admin/reviews': typeof AdminAppReviewsRoute
  '/admin/team': typeof AdminAppTeamRoute
  '/admin/hotels/$accommodationId': typeof AdminAppHotelsAccommodationIdRoute
  '/admin/motorbikes/$motorbikeId': typeof AdminAppMotorbikesMotorbikeIdRoute
  '/admin/orders/$purchaseId': typeof AdminAppOrdersPurchaseIdRoute
  '/admin/products/$productId': typeof AdminAppProductsProductIdRoute
  '/admin/settings/audit': typeof AdminAppSettingsAuditRoute
  '/admin/settings/currencies': typeof AdminAppSettingsCurrenciesRoute
  '/admin/settings/languages': typeof AdminAppSettingsLanguagesRoute
  '/admin/settings/markets': typeof AdminAppSettingsMarketsRoute
  '/admin/settings/users': typeof AdminAppSettingsUsersRoute
  '/admin/transport/$transportId': typeof AdminAppTransportTransportIdRoute
  '/admin/vouchers/$voucherId': typeof AdminAppVouchersVoucherIdRoute
  '/api/public/payments/xendit': typeof ApiPublicPaymentsXenditRoute
  '/admin/hotels': typeof AdminAppHotelsIndexRoute
  '/admin/motorbikes': typeof AdminAppMotorbikesIndexRoute
  '/admin/orders': typeof AdminAppOrdersIndexRoute
  '/admin/products': typeof AdminAppProductsIndexRoute
  '/admin/settings': typeof AdminAppSettingsIndexRoute
  '/admin/transport': typeof AdminAppTransportIndexRoute
  '/admin/vouchers': typeof AdminAppVouchersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/admin/_app': typeof AdminAppRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/admin/no-access': typeof AdminNoAccessRoute
  '/admin/setup': typeof AdminSetupRoute
  '/build-your-trip/$productId': typeof BuildYourTripProductIdRoute
  '/pages/$slug': typeof PagesSlugRoute
  '/purchase/$purchaseId': typeof PurchasePurchaseIdRoute
  '/build-your-trip/': typeof BuildYourTripIndexRoute
  '/admin/_app/catalog-taxonomy': typeof AdminAppCatalogTaxonomyRoute
  '/admin/_app/component-templates': typeof AdminAppComponentTemplatesRoute
  '/admin/_app/customers': typeof AdminAppCustomersRoute
  '/admin/_app/experiences': typeof AdminAppExperiencesRoute
  '/admin/_app/insurance': typeof AdminAppInsuranceRoute
  '/admin/_app/prices': typeof AdminAppPricesRoute
  '/admin/_app/promo-codes': typeof AdminAppPromoCodesRoute
  '/admin/_app/reviews': typeof AdminAppReviewsRoute
  '/admin/_app/team': typeof AdminAppTeamRoute
  '/admin/_app/': typeof AdminAppIndexRoute
  '/admin/_app/hotels/$accommodationId': typeof AdminAppHotelsAccommodationIdRoute
  '/admin/_app/motorbikes/$motorbikeId': typeof AdminAppMotorbikesMotorbikeIdRoute
  '/admin/_app/orders/$purchaseId': typeof AdminAppOrdersPurchaseIdRoute
  '/admin/_app/products/$productId': typeof AdminAppProductsProductIdRoute
  '/admin/_app/settings/audit': typeof AdminAppSettingsAuditRoute
  '/admin/_app/settings/currencies': typeof AdminAppSettingsCurrenciesRoute
  '/admin/_app/settings/languages': typeof AdminAppSettingsLanguagesRoute
  '/admin/_app/settings/markets': typeof AdminAppSettingsMarketsRoute
  '/admin/_app/settings/users': typeof AdminAppSettingsUsersRoute
  '/admin/_app/transport/$transportId': typeof AdminAppTransportTransportIdRoute
  '/admin/_app/vouchers/$voucherId': typeof AdminAppVouchersVoucherIdRoute
  '/api/public/payments/xendit': typeof ApiPublicPaymentsXenditRoute
  '/admin/_app/hotels/': typeof AdminAppHotelsIndexRoute
  '/admin/_app/motorbikes/': typeof AdminAppMotorbikesIndexRoute
  '/admin/_app/orders/': typeof AdminAppOrdersIndexRoute
  '/admin/_app/products/': typeof AdminAppProductsIndexRoute
  '/admin/_app/settings/': typeof AdminAppSettingsIndexRoute
  '/admin/_app/transport/': typeof AdminAppTransportIndexRoute
  '/admin/_app/vouchers/': typeof AdminAppVouchersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/admin/login'
    | '/admin/no-access'
    | '/admin/setup'
    | '/build-your-trip/$productId'
    | '/pages/$slug'
    | '/purchase/$purchaseId'
    | '/build-your-trip/'
    | '/admin/catalog-taxonomy'
    | '/admin/component-templates'
    | '/admin/customers'
    | '/admin/experiences'
    | '/admin/insurance'
    | '/admin/prices'
    | '/admin/promo-codes'
    | '/admin/reviews'
    | '/admin/team'
    | '/admin/'
    | '/admin/hotels/$accommodationId'
    | '/admin/motorbikes/$motorbikeId'
    | '/admin/orders/$purchaseId'
    | '/admin/products/$productId'
    | '/admin/settings/audit'
    | '/admin/settings/currencies'
    | '/admin/settings/languages'
    | '/admin/settings/markets'
    | '/admin/settings/users'
    | '/admin/transport/$transportId'
    | '/admin/vouchers/$voucherId'
    | '/api/public/payments/xendit'
    | '/admin/hotels/'
    | '/admin/motorbikes/'
    | '/admin/orders/'
    | '/admin/products/'
    | '/admin/settings/'
    | '/admin/transport/'
    | '/admin/vouchers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/admin/login'
    | '/admin/no-access'
    | '/admin/setup'
    | '/build-your-trip/$productId'
    | '/pages/$slug'
    | '/purchase/$purchaseId'
    | '/build-your-trip'
    | '/admin/catalog-taxonomy'
    | '/admin/component-templates'
    | '/admin/customers'
    | '/admin/experiences'
    | '/admin/insurance'
    | '/admin/prices'
    | '/admin/promo-codes'
    | '/admin/reviews'
    | '/admin/team'
    | '/admin/hotels/$accommodationId'
    | '/admin/motorbikes/$motorbikeId'
    | '/admin/orders/$purchaseId'
    | '/admin/products/$productId'
    | '/admin/settings/audit'
    | '/admin/settings/currencies'
    | '/admin/settings/languages'
    | '/admin/settings/markets'
    | '/admin/settings/users'
    | '/admin/transport/$transportId'
    | '/admin/vouchers/$voucherId'
    | '/api/public/payments/xendit'
    | '/admin/hotels'
    | '/admin/motorbikes'
    | '/admin/orders'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/transport'
    | '/admin/vouchers'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/admin/_app'
    | '/admin/login'
    | '/admin/no-access'
    | '/admin/setup'
    | '/build-your-trip/$productId'
    | '/pages/$slug'
    | '/purchase/$purchaseId'
    | '/build-your-trip/'
    | '/admin/_app/catalog-taxonomy'
    | '/admin/_app/component-templates'
    | '/admin/_app/customers'
    | '/admin/_app/experiences'
    | '/admin/_app/insurance'
    | '/admin/_app/prices'
    | '/admin/_app/promo-codes'
    | '/admin/_app/reviews'
    | '/admin/_app/team'
    | '/admin/_app/'
    | '/admin/_app/hotels/$accommodationId'
    | '/admin/_app/motorbikes/$motorbikeId'
    | '/admin/_app/orders/$purchaseId'
    | '/admin/_app/products/$productId'
    | '/admin/_app/settings/audit'
    | '/admin/_app/settings/currencies'
    | '/admin/_app/settings/languages'
    | '/admin/_app/settings/markets'
    | '/admin/_app/settings/users'
    | '/admin/_app/transport/$transportId'
    | '/admin/_app/vouchers/$voucherId'
    | '/api/public/payments/xendit'
    | '/admin/_app/hotels/'
    | '/admin/_app/motorbikes/'
    | '/admin/_app/orders/'
    | '/admin/_app/products/'
    | '/admin/_app/settings/'
    | '/admin/_app/transport/'
    | '/admin/_app/vouchers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  BuildYourTripProductIdRoute: typeof BuildYourTripProductIdRoute
  PagesSlugRoute: typeof PagesSlugRoute
  PurchasePurchaseIdRoute: typeof PurchasePurchaseIdRoute
  BuildYourTripIndexRoute: typeof BuildYourTripIndexRoute
  ApiPublicPaymentsXenditRoute: typeof ApiPublicPaymentsXenditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_app': {
      id: '/admin/_app'
      path: ''
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAppRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/no-access': {
      id: '/admin/no-access'
      path: '/no-access'
      fullPath: '/admin/no-access'
      preLoaderRoute: typeof AdminNoAccessRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/build-your-trip/': {
      id: '/build-your-trip/'
      path: '/build-your-trip'
      fullPath: '/build-your-trip/'
      preLoaderRoute: typeof BuildYourTripIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/build-your-trip/$productId': {
      id: '/build-your-trip/$productId'
      path: '/build-your-trip/$productId'
      fullPath: '/build-your-trip/$productId'
      preLoaderRoute: typeof BuildYourTripProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pages/$slug': {
      id: '/pages/$slug'
      path: '/pages/$slug'
      fullPath: '/pages/$slug'
      preLoaderRoute: typeof PagesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/purchase/$purchaseId': {
      id: '/purchase/$purchaseId'
      path: '/purchase/$purchaseId'
      fullPath: '/purchase/$purchaseId'
      preLoaderRoute: typeof PurchasePurchaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_app/': {
      id: '/admin/_app/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAppIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/catalog-taxonomy': {
      id: '/admin/_app/catalog-taxonomy'
      path: '/catalog-taxonomy'
      fullPath: '/admin/catalog-taxonomy'
      preLoaderRoute: typeof AdminAppCatalogTaxonomyRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/component-templates': {
      id: '/admin/_app/component-templates'
      path: '/component-templates'
      fullPath: '/admin/component-templates'
      preLoaderRoute: typeof AdminAppComponentTemplatesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/customers': {
      id: '/admin/_app/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminAppCustomersRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/experiences': {
      id: '/admin/_app/experiences'
      path: '/experiences'
      fullPath: '/admin/experiences'
      preLoaderRoute: typeof AdminAppExperiencesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/insurance': {
      id: '/admin/_app/insurance'
      path: '/insurance'
      fullPath: '/admin/insurance'
      preLoaderRoute: typeof AdminAppInsuranceRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/prices': {
      id: '/admin/_app/prices'
      path: '/prices'
      fullPath: '/admin/prices'
      preLoaderRoute: typeof AdminAppPricesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/promo-codes': {
      id: '/admin/_app/promo-codes'
      path: '/promo-codes'
      fullPath: '/admin/promo-codes'
      preLoaderRoute: typeof AdminAppPromoCodesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/reviews': {
      id: '/admin/_app/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminAppReviewsRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/team': {
      id: '/admin/_app/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminAppTeamRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/hotels/': {
      id: '/admin/_app/hotels/'
      path: '/hotels'
      fullPath: '/admin/hotels/'
      preLoaderRoute: typeof AdminAppHotelsIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/hotels/$accommodationId': {
      id: '/admin/_app/hotels/$accommodationId'
      path: '/hotels/$accommodationId'
      fullPath: '/admin/hotels/$accommodationId'
      preLoaderRoute: typeof AdminAppHotelsAccommodationIdRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/motorbikes/': {
      id: '/admin/_app/motorbikes/'
      path: '/motorbikes'
      fullPath: '/admin/motorbikes/'
      preLoaderRoute: typeof AdminAppMotorbikesIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/motorbikes/$motorbikeId': {
      id: '/admin/_app/motorbikes/$motorbikeId'
      path: '/motorbikes/$motorbikeId'
      fullPath: '/admin/motorbikes/$motorbikeId'
      preLoaderRoute: typeof AdminAppMotorbikesMotorbikeIdRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/orders/': {
      id: '/admin/_app/orders/'
      path: '/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminAppOrdersIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/orders/$purchaseId': {
      id: '/admin/_app/orders/$purchaseId'
      path: '/orders/$purchaseId'
      fullPath: '/admin/orders/$purchaseId'
      preLoaderRoute: typeof AdminAppOrdersPurchaseIdRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/products/': {
      id: '/admin/_app/products/'
      path: '/products'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminAppProductsIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/products/$productId': {
      id: '/admin/_app/products/$productId'
      path: '/products/$productId'
      fullPath: '/admin/products/$productId'
      preLoaderRoute: typeof AdminAppProductsProductIdRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/settings/': {
      id: '/admin/_app/settings/'
      path: '/settings'
      fullPath: '/admin/settings/'
      preLoaderRoute: typeof AdminAppSettingsIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/settings/audit': {
      id: '/admin/_app/settings/audit'
      path: '/settings/audit'
      fullPath: '/admin/settings/audit'
      preLoaderRoute: typeof AdminAppSettingsAuditRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/settings/currencies': {
      id: '/admin/_app/settings/currencies'
      path: '/settings/currencies'
      fullPath: '/admin/settings/currencies'
      preLoaderRoute: typeof AdminAppSettingsCurrenciesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/settings/languages': {
      id: '/admin/_app/settings/languages'
      path: '/settings/languages'
      fullPath: '/admin/settings/languages'
      preLoaderRoute: typeof AdminAppSettingsLanguagesRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/settings/markets': {
      id: '/admin/_app/settings/markets'
      path: '/settings/markets'
      fullPath: '/admin/settings/markets'
      preLoaderRoute: typeof AdminAppSettingsMarketsRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/settings/users': {
      id: '/admin/_app/settings/users'
      path: '/settings/users'
      fullPath: '/admin/settings/users'
      preLoaderRoute: typeof AdminAppSettingsUsersRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/transport/': {
      id: '/admin/_app/transport/'
      path: '/transport'
      fullPath: '/admin/transport/'
      preLoaderRoute: typeof AdminAppTransportIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/transport/$transportId': {
      id: '/admin/_app/transport/$transportId'
      path: '/transport/$transportId'
      fullPath: '/admin/transport/$transportId'
      preLoaderRoute: typeof AdminAppTransportTransportIdRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/vouchers/': {
      id: '/admin/_app/vouchers/'
      path: '/vouchers'
      fullPath: '/admin/vouchers/'
      preLoaderRoute: typeof AdminAppVouchersIndexRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/admin/_app/vouchers/$voucherId': {
      id: '/admin/_app/vouchers/$voucherId'
      path: '/vouchers/$voucherId'
      fullPath: '/admin/vouchers/$voucherId'
      preLoaderRoute: typeof AdminAppVouchersVoucherIdRouteImport
      parentRoute: typeof AdminAppRouteRoute
    }
    '/api/public/payments/xendit': {
      id: '/api/public/payments/xendit'
      path: '/api/public/payments/xendit'
      fullPath: '/api/public/payments/xendit'
      preLoaderRoute: typeof ApiPublicPaymentsXenditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminAppRouteRouteChildren {
  AdminAppCatalogTaxonomyRoute: typeof AdminAppCatalogTaxonomyRoute
  AdminAppComponentTemplatesRoute: typeof AdminAppComponentTemplatesRoute
  AdminAppCustomersRoute: typeof AdminAppCustomersRoute
  AdminAppExperiencesRoute: typeof AdminAppExperiencesRoute
  AdminAppInsuranceRoute: typeof AdminAppInsuranceRoute
  AdminAppPricesRoute: typeof AdminAppPricesRoute
  AdminAppPromoCodesRoute: typeof AdminAppPromoCodesRoute
  AdminAppReviewsRoute: typeof AdminAppReviewsRoute
  AdminAppTeamRoute: typeof AdminAppTeamRoute
  AdminAppIndexRoute: typeof AdminAppIndexRoute
  AdminAppHotelsAccommodationIdRoute: typeof AdminAppHotelsAccommodationIdRoute
  AdminAppMotorbikesMotorbikeIdRoute: typeof AdminAppMotorbikesMotorbikeIdRoute
  AdminAppOrdersPurchaseIdRoute: typeof AdminAppOrdersPurchaseIdRoute
  AdminAppProductsProductIdRoute: typeof AdminAppProductsProductIdRoute
  AdminAppSettingsAuditRoute: typeof AdminAppSettingsAuditRoute
  AdminAppSettingsCurrenciesRoute: typeof AdminAppSettingsCurrenciesRoute
  AdminAppSettingsLanguagesRoute: typeof AdminAppSettingsLanguagesRoute
  AdminAppSettingsMarketsRoute: typeof AdminAppSettingsMarketsRoute
  AdminAppSettingsUsersRoute: typeof AdminAppSettingsUsersRoute
  AdminAppTransportTransportIdRoute: typeof AdminAppTransportTransportIdRoute
  AdminAppVouchersVoucherIdRoute: typeof AdminAppVouchersVoucherIdRoute
  AdminAppHotelsIndexRoute: typeof AdminAppHotelsIndexRoute
  AdminAppMotorbikesIndexRoute: typeof AdminAppMotorbikesIndexRoute
  AdminAppOrdersIndexRoute: typeof AdminAppOrdersIndexRoute
  AdminAppProductsIndexRoute: typeof AdminAppProductsIndexRoute
  AdminAppSettingsIndexRoute: typeof AdminAppSettingsIndexRoute
  AdminAppTransportIndexRoute: typeof AdminAppTransportIndexRoute
  AdminAppVouchersIndexRoute: typeof AdminAppVouchersIndexRoute
}

const AdminAppRouteRouteChildren: AdminAppRouteRouteChildren = {
  AdminAppCatalogTaxonomyRoute: AdminAppCatalogTaxonomyRoute,
  AdminAppComponentTemplatesRoute: AdminAppComponentTemplatesRoute,
  AdminAppCustomersRoute: AdminAppCustomersRoute,
  AdminAppExperiencesRoute: AdminAppExperiencesRoute,
  AdminAppInsuranceRoute: AdminAppInsuranceRoute,
  AdminAppPricesRoute: AdminAppPricesRoute,
  AdminAppPromoCodesRoute: AdminAppPromoCodesRoute,
  AdminAppReviewsRoute: AdminAppReviewsRoute,
  AdminAppTeamRoute: AdminAppTeamRoute,
  AdminAppIndexRoute: AdminAppIndexRoute,
  AdminAppHotelsAccommodationIdRoute: AdminAppHotelsAccommodationIdRoute,
  AdminAppMotorbikesMotorbikeIdRoute: AdminAppMotorbikesMotorbikeIdRoute,
  AdminAppOrdersPurchaseIdRoute: AdminAppOrdersPurchaseIdRoute,
  AdminAppProductsProductIdRoute: AdminAppProductsProductIdRoute,
  AdminAppSettingsAuditRoute: AdminAppSettingsAuditRoute,
  AdminAppSettingsCurrenciesRoute: AdminAppSettingsCurrenciesRoute,
  AdminAppSettingsLanguagesRoute: AdminAppSettingsLanguagesRoute,
  AdminAppSettingsMarketsRoute: AdminAppSettingsMarketsRoute,
  AdminAppSettingsUsersRoute: AdminAppSettingsUsersRoute,
  AdminAppTransportTransportIdRoute: AdminAppTransportTransportIdRoute,
  AdminAppVouchersVoucherIdRoute: AdminAppVouchersVoucherIdRoute,
  AdminAppHotelsIndexRoute: AdminAppHotelsIndexRoute,
  AdminAppMotorbikesIndexRoute: AdminAppMotorbikesIndexRoute,
  AdminAppOrdersIndexRoute: AdminAppOrdersIndexRoute,
  AdminAppProductsIndexRoute: AdminAppProductsIndexRoute,
  AdminAppSettingsIndexRoute: AdminAppSettingsIndexRoute,
  AdminAppTransportIndexRoute: AdminAppTransportIndexRoute,
  AdminAppVouchersIndexRoute: AdminAppVouchersIndexRoute,
}

const AdminAppRouteRouteWithChildren = AdminAppRouteRoute._addFileChildren(
  AdminAppRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminAppRouteRoute: typeof AdminAppRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNoAccessRoute: typeof AdminNoAccessRoute
  AdminSetupRoute: typeof AdminSetupRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAppRouteRoute: AdminAppRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminNoAccessRoute: AdminNoAccessRoute,
  AdminSetupRoute: AdminSetupRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  BuildYourTripProductIdRoute: BuildYourTripProductIdRoute,
  PagesSlugRoute: PagesSlugRoute,
  PurchasePurchaseIdRoute: PurchasePurchaseIdRoute,
  BuildYourTripIndexRoute: BuildYourTripIndexRoute,
  ApiPublicPaymentsXenditRoute: ApiPublicPaymentsXenditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
